export const FILTER_ORDERS_STATUS = 'ORDERS/FILTER_BY_STATUS';
export const FILTER_ORDERS_PAYMENT = 'ORDERS/FILTER_BY_PAYMENT';
export const FILTER_ORDERS_FULFILLMENT = 'ORDERS/FILTER_BY_FULFILLMENT';

export const FETCH_SHOPS = 'SHOPS/FETCH_SHOPS';

export const FETCH_ORDERS = 'ORDERS/FETCH_ORDERS';

export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';

