export const FETCH_SHOPS = 'SHOPS/FETCH_SHOPS';

export const FETCH_CUSTOMERS = 'CUSTOMERS/FETCH_CUSTOMERS';

export const FILTER_ORDERS_STATUS = 'ORDERS/FILTER_BY_STATUS';
export const FILTER_ORDERS_REFUND = 'ORDERS/FILTER_BY_REFUND';
export const FILTER_ORDERS_FULFILLMENT = 'ORDERS/FILTER_BY_FULFILLMENT';
export const FETCH_ORDERS = 'ORDERS/FETCH_ORDERS';
export const FETCH_ORDER_INFO = 'ORDERS/FETCH_ORDER_INFO';

export const POPUP_SHOW_POPUP = 'POPUP/SHOW_POPUP';
export const POPUP_HIDDEN_POPUP = 'POPUP/HIDDEN_POPUP';

export const NAVIGATION_CHANGE_NAVIGATION = 'NAVIGATION/CHANGE_NAVIGATION';
