export const FETCH_SHOPS = 'SHOPS/FETCH_SHOPS';

export const FILTER_ORDERS_STATUS = 'ORDERS/FILTER_BY_STATUS';
export const FILTER_ORDERS_REFUND = 'ORDERS/FILTER_BY_REFUND';
export const FILTER_ORDERS_FULFILLMENT = 'ORDERS/FILTER_BY_FULFILLMENT';

export const FETCH_ORDERS = 'ORDERS/FETCH_ORDERS';
export const FETCH_ORDER_INFO = 'ORDERS/FETCH_ORDER_INFO';

export const APP_SHOW_POPUP = 'APP/SHOW_POPUP';
export const APP_HIDDEN_POPUP = 'APP/HIDDEN_POPUP';
export const APP_SHOW_LOADER = 'APP/SHOW_LOADER';
export const APP_HIDE_LOADER = 'APP/HIDE_LOADER';
